export default [
  { code: 'af', name: 'Afrikaans', flag: 'https://flagcdn.com/za.svg' },
  { code: 'sq', name: 'Shqip', flag: 'https://flagcdn.com/al.svg' },
  { code: 'am', name: 'አማርኛ', flag: 'https://flagcdn.com/et.svg' },
  { code: 'en-AU', name: 'English (Australia)', flag: 'https://flagcdn.com/au.svg' },
  { code: 'en-CA', name: 'English (Canada)', flag: 'https://flagcdn.com/ca.svg' },
  { code: 'en-GB', name: 'English (United Kingdom)', flag: 'https://flagcdn.com/gb.svg' },
  { code: 'en', name: 'English', flag: 'https://flagcdn.com/us.svg' },
  { code: 'ar', name: 'العربية', flag: 'https://flagcdn.com/sa.svg' },
  { code: 'hy', name: 'Հայերեն', flag: 'https://flagcdn.com/am.svg' },
  { code: 'my', name: 'ဗမာ', flag: 'https://flagcdn.com/mm.svg' },
  { code: 'eu', name: 'Euskara', flag: 'https://flagcdn.com/es.svg' },
  { code: 'bn', name: 'বাংলা', flag: 'https://flagcdn.com/bd.svg' },
  { code: 'bg', name: 'Български', flag: 'https://flagcdn.com/bg.svg' },
  { code: 'be', name: 'Беларуская', flag: 'https://flagcdn.com/by.svg' },
  { code: 'hr', name: 'Hrvatski', flag: 'https://flagcdn.com/hr.svg' },
  { code: 'da', name: 'Dansk', flag: 'https://flagcdn.com/dk.svg' },
  { code: 'et', name: 'Eesti', flag: 'https://flagcdn.com/ee.svg' },
  { code: 'tl', name: 'Filipino', flag: 'https://flagcdn.com/ph.svg' },
  { code: 'fi', name: 'Suomi', flag: 'https://flagcdn.com/fi.svg' },
  { code: 'fr-FR', name: 'Français (France)', flag: 'https://flagcdn.com/fr.svg' },
  { code: 'fr-CA', name: 'Français (Canada)', flag: 'https://flagcdn.com/ca.svg' },
  { code: 'gl', name: 'Galego', flag: 'https://flagcdn.com/es.svg' },
  { code: 'ka', name: 'ქართული', flag: 'https://flagcdn.com/ge.svg' },
  { code: 'gu', name: 'ગુજરાતી', flag: 'https://flagcdn.com/in.svg' },
  { code: 'he', name: 'עברית', flag: 'https://flagcdn.com/il.svg' },
  { code: 'hi', name: 'हिन्दी', flag: 'https://flagcdn.com/in.svg' },
  { code: 'id', name: 'Indonesia', flag: 'https://flagcdn.com/id.svg' },
  { code: 'is', name: 'Íslenska', flag: 'https://flagcdn.com/is.svg' },
  { code: 'it', name: 'Italiano', flag: 'https://flagcdn.com/it.svg' },
  { code: 'ja', name: '日本語', flag: 'https://flagcdn.com/jp.svg' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: 'https://flagcdn.com/in.svg' },
  { code: 'ca', name: 'Català', flag: 'https://flagcdn.com/es.svg' },
  { code: 'kk', name: 'Қазақ тілі', flag: 'https://flagcdn.com/kz.svg' },
  { code: 'km', name: 'ខ្មែរ', flag: 'https://flagcdn.com/kh.svg' },
  { code: 'ko', name: '한국어', flag: 'https://flagcdn.com/kr.svg' },
  { code: 'ky', name: 'Кыргызча', flag: 'https://flagcdn.com/kg.svg' },
  { code: 'lo', name: 'ລາວ', flag: 'https://flagcdn.com/la.svg' },
  { code: 'lt', name: 'Lietuvių', flag: 'https://flagcdn.com/lt.svg' },
  { code: 'lv', name: 'Latviešu', flag: 'https://flagcdn.com/lv.svg' },
  { code: 'mk', name: 'Македонски', flag: 'https://flagcdn.com/mk.svg' },
  { code: 'ml', name: 'മലയാളം', flag: 'https://flagcdn.com/in.svg' },
  { code: 'ms-MY', name: 'Bahasa Melayu (Malaysia)', flag: 'https://flagcdn.com/my.svg' },
  { code: 'ms', name: 'Bahasa Melayu', flag: 'https://flagcdn.com/my.svg' },
  { code: 'mr', name: 'मराठी', flag: 'https://flagcdn.com/in.svg' },
  { code: 'hu', name: 'Magyar', flag: 'https://flagcdn.com/hu.svg' },
  { code: 'mn', name: 'Монгол', flag: 'https://flagcdn.com/mn.svg' },
  { code: 'ne', name: 'नेपाली', flag: 'https://flagcdn.com/np.svg' },
  { code: 'nl', name: 'Nederlands', flag: 'https://flagcdn.com/nl.svg' },
  { code: 'no', name: 'Norsk', flag: 'https://flagcdn.com/no.svg' },
  { code: 'de', name: 'Deutsch', flag: 'https://flagcdn.com/de.svg' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: 'https://flagcdn.com/in.svg' },
  { code: 'fa', name: 'فارسی', flag: 'https://flagcdn.com/ir.svg' },
  { code: 'pl', name: 'Polski', flag: 'https://flagcdn.com/pl.svg' },
  { code: 'pt-BR', name: 'Português (Brasil)', flag: 'https://flagcdn.com/br.svg' },
  { code: 'pt-PT', name: 'Português (Portugal)', flag: 'https://flagcdn.com/pt.svg' },
  { code: 'ro', name: 'Română', flag: 'https://flagcdn.com/ro.svg' },
  { code: 'ru', name: 'Русский', flag: 'https://flagcdn.com/ru.svg' },
  { code: 'rm', name: 'Rumantsch', flag: 'https://flagcdn.com/ch.svg' },
  { code: 'si', name: 'සිංහල', flag: 'https://flagcdn.com/lk.svg' },
  { code: 'sk', name: 'Slovenčina', flag: 'https://flagcdn.com/sk.svg' },
  { code: 'sl', name: 'Slovenščina', flag: 'https://flagcdn.com/si.svg' },
  { code: 'sr', name: 'Српски', flag: 'https://flagcdn.com/rs.svg' },
  { code: 'sw', name: 'Kiswahili', flag: 'https://flagcdn.com/tz.svg' },
  { code: 'ta', name: 'தமிழ்', flag: 'https://flagcdn.com/in.svg' },
  { code: 'te', name: 'తెలుగు', flag: 'https://flagcdn.com/in.svg' },
  { code: 'th', name: 'ไทย', flag: 'https://flagcdn.com/th.svg' },
  { code: 'tr', name: 'Türkçe', flag: 'https://flagcdn.com/tr.svg' },
  { code: 'uk', name: 'Українська', flag: 'https://flagcdn.com/ua.svg' },
  { code: 'ur', name: 'اردو', flag: 'https://flagcdn.com/pk.svg' },
  { code: 'vi', name: 'Tiếng Việt', flag: 'https://flagcdn.com/vn.svg' },
  { code: 'zu', name: 'Zulu', flag: 'https://flagcdn.com/za.svg' },
  { code: 'az', name: 'Azərbaycan dili', flag: 'https://flagcdn.com/az.svg' },
  { code: 'cs', name: 'Čeština', flag: 'https://flagcdn.com/cz.svg' },
  { code: 'zh-HK', name: '中文（香港）', flag: 'https://flagcdn.com/hk.svg' },
  { code: 'zh-TW', name: '中文（繁體）', flag: 'https://flagcdn.com/tw.svg' },
  { code: 'zh', name: '中文（简体）', flag: 'https://flagcdn.com/cn.svg' },
  { code: 'el', name: 'Ελληνικά', flag: 'https://flagcdn.com/gr.svg' },
  { code: 'es-419', name: 'Español (Latinoamérica)', flag: 'https://flagcdn.com/latam.svg' },
  { code: 'es-US', name: 'Español (Estados Unidos)', flag: 'https://flagcdn.com/us.svg' },
  { code: 'es', name: 'Español (España)', flag: 'https://flagcdn.com/es.svg' },
  { code: 'sv', name: 'Svenska', flag: 'https://flagcdn.com/se.svg' },
] as const
